# Generated by Django 5.1.1 on 2024-09-08 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('user', '0002_web3user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='token_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ImagePromptTransaction',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('processed', 'Processed')], default='created', max_length=10)),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.web3user')),
            ],
        ),
    ]
