# Generated by Django 5.1.1 on 2024-09-08 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_token_id_imageprompttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprompttransaction',
            name='token_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageprompttransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
